### ISSUE TITLE
No warnings for missing AddressableImportSettingsasset

### ISSUE THREAD

**Issue by EgilSandfeld** [favoyang/unity-addressable-importer#15]
Checking out this plugin and found an issue when I created the AddressableImportSettings asset using the [Usage docs](https://github.com/favoyang/unity-addressable-importer/blob/master/Documentation~/AddressableImporter.md#setup-the-importer). It gave me no errors or warnings, but the following code returned me:

`var importSettings = AddressableImportSettings.Instance;
        if (importSettings == null || importSettings.rules == null || importSettings.rules.Count == 0)
            return;`

I figured to move the AddressableImportSettings asset to _Assets/AddressableAssetsData_ and it worked. 

Perhaps a warning or allowing the asset to be placed elsewhere would be great :)

**Comment by favoyang** [comment]
Personally I prefer convention over configuration, so I would like to keep the settings file under Assets/AddressableAssetsData. But a warning is helpful indeed.

**Comment by favoyang** [comment]
Fixed in https://github.com/favoyang/unity-addressable-importer/commit/30dd56a0823e0f370d775acbce06736a92c0dafb
