### ISSUE TITLE
I cannot set an address to a directory

### ISSUE THREAD

**Issue by masak2** [favoyang/unity-addressable-importer#26]
Path:Assets/Addressable/Test$
MatchType:Regex

This does not set an address.

Path:Assets/Addressable/Test
MatchType:Wildcard
This sets address to all fiels under Test directory.

I hope to be fixed that this addon sets an address to any directory.

**Comment by favoyang** [comment]
This should work, when you use `Context menu > Reimport` (or just create the `Test` folder). 
- Path: `^Assets/Addressable/Test$`
- MatchType: Regex

But failed with `Context menu > Addressable Importer > Check Folder(s)`, which won't send directory itself to the importer. The behavior is inconsistent. I consider it a bug.

**Comment by favoyang** [comment]
@masak2,

Please check out v0.7.1 and docs https://github.com/favoyang/unity-addressable-importer/blob/master/Documentation~/AddressableImporter.md#rule-examples

**Comment by masak2** [comment]
Thanks, it works well.
