### ISSUE TITLE
If group names contain slashes, incorrect groups are created

### ISSUE THREAD

**Issue by eAi** [favoyang/unity-addressable-importer#27]
I have a rule set up that (incorrectly) has a slash in the group name. This is replaced by addressables with a - symbol. This breaks the logic in CreateOrUpdateAddressableAssetEntry that tries to find an existing group - as this logic doesn't take into account this replacement behaviour - so never finds a group. The result of this is that duplicate groups are created (by addressables) when CreateAssetGroup is called - if there is more than one asset in the group.

Steps to reproduce: 
- Create a rule that applies to more than one asset
- Set the group name to contain a slash
- Apply the rules using the context menu
- Notice you have more than one group created, one containing each item with a 1/2/3 (etc) suffix added.

What I'd expect to happen:
Either slashes are forbidden in the group names and gives the user an error, or the logic in CreateOrUpdateAddressableAssetEntry has some understanding of how addressables does replacement of symbols in groups and handles this the same way. The logic for this is in the AddressableAssetGroup.Name property.

**Comment by favoyang** [comment]
Taking the second suggestion - clean the group name internally before sending it to create group function.

But I may add the otherwise either if I find a good way to validate a nested editor field in the current implementation.

**Comment by favoyang** [comment]
@eAi, thank you for the help. I've added you as a contributor to the README.

**Comment by eAi** [comment]
My pleasure - thanks for creating this!
