### ISSUE TITLE
Ticking the "Remove Empty Groups" tickbox stops empty groups being created anywhere

### ISSUE THREAD

**Issue by eAi** [favoyang/unity-addressable-importer#28]
This may be by design, but certainly confused me: Having the Remove Empty Groups tick box prevents groups being created manually in the Addressables Groups window - as these are empty by default. 

Steps to reproduce:
- Tick the Remove Empty Groups tickbox in the import settings file
- Open the Addressables Groups window
- Right click and select Create New Group > Packed Assets
- Notice that nothing happens

Ideally, this tickbox wouldn't do anything to manually created groups - just those that had been created by the import process. This would probably require tracking these groups in some way. Could a new class be created that derives from AddressableAssetGroup that is used to mark groups that are 'managed' by the importer? Alternatively, a big warning on this tickbox might help - it does seem quite dangerous!

**Comment by favoyang** [comment]
You made the point. But it's not ideal to implement such a thing without a visible way to show users whether a group is managed. What if a user creates a managed group, then delete the rule, the group is managed or not?

Alternatively, I propose to retire the feature and replaced it with a [clean empty groups] button.
