### ISSUE TITLE
Odin Inspector Support

### ISSUE THREAD

**Issue by Mefodei** [favoyang/unity-addressable-importer#32]
Hello again.

I'm here to ask you about Odin Inspector support feature
Right now Inspector looks like

https://i.gyazo.com/a8c27e2a952afa27ea9502085b20a70a.png

with Odin it can be more pretty, but you override base  imgui drawer. You can use "ODIN INSPECTOR" define for detect Odin features support.

**Comment by favoyang** [comment]
Hi @Mefodei,

Thanks for the idea. Odin looks interesting, but it also needs to clarify what happens if I only reference Odin's namespace with the MIT license. I would be more preferer to depends on an Open Source alternative, but I didn't find a comparable one.

**Comment by Mefodei** [comment]
U can wrap all usage with #IF ODIN_INSPECTOR defines and use all Odin inspector Attributes by Full Namespace. For example:
`
#if ODIN_INSPECTOR
        [Sirenix.OdinInspector.Button]
#endif
        public void Done()
        {
            
        }
`

**Comment by favoyang** [comment]
Thanks for the example.

I have sent an email to ODIN support to clarify the license issue. I need an official response from them to make sure it's legal to adding ODIN support the way you suggested. I will post the response to this thread when they reply. 

Overall, I'm not that engaged to add extra support for commercial software, but adding ODIN support can be a workaround to improve UX before the next major release, which requires refactor the current inspector to a window (TBD). https://github.com/favoyang/unity-addressable-importer/issues/25#issuecomment-629682727. That means the ODIN support maybe reverted later.

If I get a positive response from the ODIN team, with all the above considered, would you want to implement the feature as a PR?

**Comment by favoyang** [comment]
The reply from ODIN is yes, there's no legal issue your way.

**Comment by Mefodei** [comment]
Yes, i can make Odin support PR

**Comment by favoyang** [comment]
Sounds great!

**Comment by Mefodei** [comment]
Push new PR with odin support feature

**Comment by favoyang** [comment]
Please checkout the code review for #33.

**Comment by Mefodei** [comment]
update review fixes

**Comment by favoyang** [comment]
BTW, my review was updated.

**Comment by favoyang** [comment]
@all-contributors please add @Mefodei for code
