### ISSUE TITLE
Search Filter For registered paths

### ISSUE THREAD

**Issue by Mefodei** [favoyang/unity-addressable-importer#34]
Hi again.
If Addressables Importing rules more than 10, then it very difficult to find target rules. May be good decision add Search input field to filter rules.

**Comment by favoyang** [comment]
Thanks for the idea. Is this easy to achieve in current architecture? Or it could be postponed with #25 to the next UX refactor.

**Comment by Mefodei** [comment]
Hi. 
It easy implement for Odin/ImGUI. 
You notice about ui refactoring. Are you think about UIElement?

**Comment by favoyang** [comment]
Yes, I intended to delay all major UI feature until the UIElement refactor.

**Comment by Mefodei** [comment]
https://github.com/favoyang/unity-addressable-importer/pull/35 - related to previous PR with Odin Support

**Comment by favoyang** [comment]
Closed by #35
