### ISSUE TITLE
is there a way to add a new label from importSettings

### ISSUE THREAD

**Issue by hyhmm** [favoyang/unity-addressable-importer#37]

**Comment by favoyang** [comment]
Nope for the current implementation, which uses a label array to reference existing labels.

```cs
List<AssetLabelReference> labelRefs;
```

However, the underlying AddressableAssetEntry entry has a SetLabel method with a force parameter to create a new label via code. So it should be possible.

```cs
public bool SetLabel(string label, bool enable, bool force = false, bool postEvent = true)
```

But we have to consider both backward compatibility and UX.
- For the backward compatibility I'd like to keep current labelRefs array.
- For UX, one workaround is to add another array of string for dynamic label replacement (like group replacement), or even better it can support a good UX by letting users search existing labels, or add a new one at the same time. Like the "tag" input field of modern web UI.
