### ISSUE TITLE
From Folder To  AddressableGroup Setter (use if you find useful )

### ISSUE THREAD

**Issue by SujanDuttaMishra** [favoyang/unity-addressable-importer#38]
hello author users
great work congrats,
while i was using this i found it was very inconvenient to actually go fill the list  , thus i figured out a solution : why not have additional so which can be added on any folder root that we want to convert to addressable objects group . thus with this in mind i created a so which does just that.

For now add the following 2 script / or copy paste create them scroll to end
https://1drv.ms/u/s!AsuS2SZQnqeG-XG_Flw4p862qxPW?e=aYgb7k
Admin Creator please fill free to modify and merge it into your repo if you feel is good addition.

how to use :
just navigate to desired folder , right click anywhere within that folder , AddressableImporter: Set FromFolder , just where we find AddressableImporter: checkFolder(s);
this will create a scriptable object with a rule tied to main AddressableImportSettings instance and adds the rule.
settings to configure are
A ) addressableAssetSettingsName , by default if you havenot changed original AddressableAssetSettings name "AddressableAssetSettings" should point you to correct setting file, otherwise go find it in AddressableAssetData Folder
B) groupTemplateName , i have set it to remote , because i have a remote setup, if you dont have go find this settings under AddressableAssetsData\AssetGroupTemplates , once found just set it to that name or just drag drop to feild "template"
C) settings : you can either drap drop or find name and set it in addressableAssetSettingsName 
D) template : you can either drap drop or find name and set it in groupTemplateName 
E) PreLoad : usally we would have a lable attached to addressablegroup as to load on Start /Awake , if you dont want keet it to none, if you want use onstart or on awake ... this will add a lable OnStart / Onawake , which you can then use as filter to load instantiale accordingly
F) Add Lable : In case you want to add any other  custom Lable to the folder containt. it will check if it exist then if not adds a new Lable
G ) Rule  : settings for rule 
H ) Auto Fill : fills Rules 
I) Save : deploy Save method under main AddressableImportSettings.Instance

How to edit rule of folder  later : 
go to folder , select the so with foldername .. follow inspector

******* script A FolderAddressableSetter.cs ****

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityAddressableImporter.Helper;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEngine;
using UnityEngine.AddressableAssets;
using Object = UnityEngine.Object;

public class FolderAddressableSetter : ScriptableObject
{
    private AddressableImportSettings Instance { get; set; }
    public string addressableAssetSettingsName = "AddressableAssetSettings";
    public string groupTemplateName = "Remote";
    public AddressableAssetSettings settings;
    public AddressableAssetGroupTemplate template;
    public Load preLoad = Load.None;
    public string addLabel = string.Empty;

#if ODIN_INSPECTOR
    [Sirenix.OdinInspector.ListDrawerSettings(HideAddButton = false,Expanded = false,DraggableItems = true,HideRemoveButton = false)]
#endif
    [Tooltip("Rules for Managing assets In this Folder.")]
    public AddressableImportRule rule;

    private void OnEnable()
    {
        Instance = AddressableImportSettings.Instance;
        CreateInstanceIfNull();
        settings = GetInstances<AddressableAssetSettings>(addressableAssetSettingsName);
        template = GetInstances<AddressableAssetGroupTemplate>(groupTemplateName);

        AutoFill();
    }

    [MenuItem("Assets/AddressableImporter: Set FromFolder")]
    private static void CreateInstance()
    {
        var path = GetPath(out var directory);
        var instance = CreateInstance<FolderAddressableSetter>();
        AssetDatabase.CreateAsset(instance, AssetDatabase.GenerateUniqueAssetPath(path + $"/{directory}.asset"));
        AssetDatabase.SaveAssets();

    }

    [ButtonMethod]
    private void AutoFill()
    {

        if (addressableAssetSettingsName != "AddressableAssetSettings")
        {
            var temp = GetInstances<AddressableAssetSettings>(addressableAssetSettingsName);
            settings = temp != null ? temp : settings;
            addressableAssetSettingsName = settings.name;
        }
        if (groupTemplateName != "Remote")
        {
            var temp = GetInstances<AddressableAssetGroupTemplate>(groupTemplateName);
            template = temp != null ? temp : template;
            groupTemplateName = template.name;
        }

        var path = GetPath(out var directory);

        rule = new AddressableImportRule
        {
            path = path,
            groupName = directory,
            LabelMode = LabelWriteMode.Replace,
            groupTemplate = template,
            groupTemplateApplicationMode = GroupTemplateApplicationMode.AlwaysOverwriteGroupSettings,
            simplified = true
        };

        switch (preLoad)
        {
            case Load.OnStart:
                rule.labelRefs = new List<AssetLabelReference>();
                SetLabel(directory);
                SetLabel("OnStart");
                break;
            case Load.OnAwake:
                rule.labelRefs = new List<AssetLabelReference>();
                SetLabel(directory);
                SetLabel("OnAwake");
                break;
            case Load.None:
                rule.labelRefs = new List<AssetLabelReference>();
                SetLabel(directory);
                break;
            default:
                throw new ArgumentOutOfRangeException();
        }

        if (!string.IsNullOrEmpty(addLabel)) SetLabel(addLabel);

    }

    private static string GetPath(out string directory)
    {
        var path = AssetDatabase.GetAssetPath(Selection.activeObject);
        directory = Path.GetFileNameWithoutExtension(path);
        if (path == "")
        {
            path = "Assets";
        }
        else if (Path.GetExtension(path) != "")
        {
            path = path.Replace(Path.GetFileName(path), "*");
        }

        return path;
    }

    [ButtonMethod]
    private void Save()
    {
        var list = Instance.rules;
        var have = list.Find(o => o.path == rule.path);
       // Debug.Log($" have:> {have != null} :::  rule path {rule.path}");
       if (have == null)
        {
            Instance.rules.Add(rule);
          //  Debug.Log($"rule {rule.groupName} @ {rule.path} added");
        }
        else
        {
            list.RemoveAll(o => o.path == rule.path);
            Instance.rules.Add(rule);
          //  Debug.Log($"rule {rule.groupName} @ {rule.path} Replaced");
        }
        Instance.Save();

        var path = GetPath(out var directory);
        path = path.Replace($"/*", "");
        AddressableImporter.FolderImporter.ReimportFolders(new string[] { path });
    }

    private void CreateInstanceIfNull()
    {
        if (Instance == null)
        {
            var asset = CreateInstance<AddressableImportSettings>();
            AssetDatabase.CreateAsset(asset, AddressableImportSettings.kDefaultPath);
            AssetDatabase.SaveAssets();
           
        }
        Instance = AddressableImportSettings.Instance;

    }

    private void SetLabel(string label)
    {

        var get = settings.GetLabels();
        if (!get.Contains(label)) settings.AddLabel(label);
        var assetLabel = new AssetLabelReference { labelString = label };
        rule.labelRefs.Add(assetLabel);

    }

    public T GetInstances<T>(string assetName) where T : ScriptableObject
    {
        T asset = null;
        var assetList = GetAllInstances<T>();
        asset = assetList.FirstOrDefault(o => o.name == assetName);
        if (asset != null) return asset;
        asset = assetList.FirstOrDefault();
        return asset;
    }

    public List<T> GetAllInstances<T>() where T : ScriptableObject
    {
        var assetList = Resources.FindObjectsOfTypeAll<T>().ToList();
        return assetList;
    }

    private void OnDestroy()
    {

        Remove();

    }

    [ButtonMethod]
    private void Remove()
    {
        var rulePath = rule.path;
        var groupName = rule.groupName;
        var rules = Instance.rules.FindAll(o => o.path == rulePath || o.groupName == groupName);

        for (int i = 0; i < rules.Count; i++)
        {
            var item = rules[i];
            Debug.Log($" Remove:> {item} @  path {rulePath} Of groupName {groupName} ");
            Instance.rules.Remove(item);
        }

        var labels = settings.GetLabels();
        var contains = labels.Contains(groupName);
        Debug.Log($"contains {contains} groupName {groupName} ");
        if (contains) settings.RemoveLabel(groupName);

        //var instance = GetInstances<FolderAddressableSetter>(groupTemplateName);
        //if (instance != null) DestroyImmediate(instance, true);
    }

    public enum Load
    {
        OnStart, OnAwake, None
    }
}

*******end*****

******* script B FolderAddressableSetterEditor.cs  " make a folder called Editor and put this script ****

using UnityEngine;
namespace UnityAddressableImporter.Helper.Internal
{
    using System;
    using System.Collections.Generic;
    using System.Reflection;
    using Editor.Helper;
    using UnityEditor;

    [CustomEditor(typeof(FolderAddressableSetter), true), CanEditMultipleObjects]
    public class FolderAddressableSetterEditor : Editor
    {
        private List<MethodInfo> _methods;
        private ScriptableObject _target;
        private AddressableImporterOdinHandler _drawer;

        private void OnEnable()
        {
            _target = target as ScriptableObject;
            _drawer = _drawer ?? new AddressableImporterOdinHandler();
            if (_target == null) return;

            _drawer.Initialize(target);
            _methods = AddressableImporterMethodHandler.CollectValidMembers(_target.GetType());
        }

        private void OnDisable()
        {
            _drawer.Dispose();
        }

        public override void OnInspectorGUI()
        {
            DrawBaseEditor();

            if (_methods == null) return;

            AddressableImporterMethodHandler.OnInspectorGUI(_target, _methods);
        }

        private void DrawBaseEditor()
        {
#if ODIN_INSPECTOR
			_drawer.Draw();
#else
            base.OnInspectorGUI();
#endif
        }
    }
}

*******end*****

**Comment by favoyang** [comment]
@SujanDuttaMishra 

Thanks for sharing your idea. If I understand correctly what you proposed is an importer's importer, by creating an intermediary per-folder setting file (the scriptable object) and use that file's inspector's save/remove buttons to sync with the main addressable importer setting file. This can be a pragmatic practice, what I don't like is that it may bring more inconsistent states because the per-folder importer is only one-way manually synced to the main importer. But it is a design decision.

I agree that add/find/modify the rules matched with the selected folder/files can be painful if you have many rules. Especially if you don't lock the inspector, and trying to click back and forth. I would prefer another approach:
- implement the importer's inspector as a dedicated editor window, so you never have the issue to lose focus.
- add a button to add a rule for your selected asset(s).
- add a filter button to filter existing rules for selected assets(s).
- Of course, this is won't happen recently until the next big UX focused release.

Again, thanks for sharing your idea.

**Comment by SujanDuttaMishra** [comment]
Hello,
my idea is to have scriptable object in each folder that we want to register as addressable, that fills up the rule and post it to main script list too.  in the code i have shared it all done and works fine , need a bit of optimization. major ease comes with this is we don't have to worry about filling in each entry manually, also if we are to share addressable with other project its much easier. in my case i have made a folder "AssetData"  and within that folder i have sub and sub to sub folders tree, that holds various type of remote/local/ etc assets to be, this work as an extension to your project ,everything else goes via main code. just adding entry happens easier and almost automatic . give it a try .

**Comment by favoyang** [comment]
Yeah, thanks for sharing the code, and that is basically what I described "intermediary per-folder setting file(s)". I'm not going to merge this, but I agree that it can be a pragmatic practice. If you'd like to organize the code base into another extension package you managed, I could add a link to README to mention it.

I will close it for now. But feel free to continue the conversation on this thread.

**Comment by SujanDuttaMishra** [comment]
Thanks, 
 I will keep it as it now for if anyone stumbling can use it if they feel , will update code whenever i do something new.. For me i really need this method, as i have 1000s of asset, later as i go i will see if i can swap/have different catalog,populate from remote etc.  i am not great at managing repo etc so i will just leave it like that.

**Comment by favoyang** [comment]
Sounds good.
