### ISSUE TITLE
Can't use the importer without Odin v0.9.0

### ISSUE THREAD

**Issue by ReOcto** [favoyang/unity-addressable-importer#39]
Exception:
```
Library/PackageCache/com.littlebigfun.addressable-importer@0.9.0/Editor/Helper/AddressableImportSettingsEditor.cs(21,11): error CS0246: The type or namespace name 'AddressableImporterOdinHandler' could not be found (are you missing a using directive or an assembly reference?)
```

Seems like the bug is caused by mistake in naming:
AddressablesImporterOdinHandler >> AddressableImporterOdinHandler

**Comment by favoyang** [comment]
@ReOcto thanks for reporting the bug. I thought it was fixed before, but seems been reverted recently. Please give 0.9.1 a try.
