### ISSUE TITLE
Constantly warn about missing settings

### ISSUE THREAD

**Issue by laicasaane** [favoyang/unity-addressable-importer#40]
This warning has been bugging me for a while, I don't understand what's wrong here. Everything else works without problem though.

```
[Addressables] settings file not found.
Please go to Menu/Window/Asset Management/Addressables, then click 'Create Addressables Settings' button.
UnityEngine.Debug:LogWarningFormat(String, Object[])
AddressableImporter:OnPostprocessAllAssets(String[], String[], String[], String[]) (at Library/PackageCache/com.littlebigfun.addressable-importer@0.9.1/Editor/AddressableImporter.cs:28)
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets(String[], String[], String[], String[], String[])
```

**Comment by favoyang** [comment]
It's a helper text designed to notify a user to create an addressable setting file before using the importer.

But it seems buggy when compiling scripts trigger the importer. Maybe during the process, the Addressable setting file is re-deserializing and caused the instance variable to be reset first, and caused the importer's query to fail.

I need some time to investigate it but may end up with just removing the helper text.
