### ISSUE TITLE
Missing meta file error at every reload

### ISSUE THREAD

**Issue by EmyEdoki** [favoyang/unity-addressable-importer#41]
The error is this:
"Asset Packages/com.littlebigfun.addressable-importer/Media/icon.asset has no meta file, but it's in an immutable folder. The asset will be ignored."

**Comment by favoyang** [comment]
Weird, it seems an error of a very early version.

All files under the Media folder has meta files.
![image](https://user-images.githubusercontent.com/125390/96286653-4ef47a00-1013-11eb-9cef-176cc8c6528f.png)

So which version you installed?

**Comment by EmyEdoki** [comment]
Yes it the latest version.
![2020-10-16 14_59_36-Window](https://user-images.githubusercontent.com/50375630/96298409-66eede00-0fc0-11eb-9691-e1d066f18710.png)
icon.asset seem to be generated by unity somehow.
![2020-10-16 15_00_24-Window](https://user-images.githubusercontent.com/50375630/96298421-69e9ce80-0fc0-11eb-830f-6cd6d1ca8163.png)

**Comment by favoyang** [comment]
It seems generated from the `icon.svg` file,  the one shares the same filename.

I upgrade to Unity 2020.20b6, I didn't see the auto-generated `icon.asset` file.

**Comment by favoyang** [comment]
I decided to move the `Media` folder to `Media~` folder to avoid such weird things.
