### ISSUE TITLE
排除规则有吗？

### ISSUE THREAD

**Issue by zuig** [favoyang/unity-addressable-importer#42]
排除规则怎么定义？
如 ui/* 是通配ui目录下的所有文件夹，但里面有一个 ui/test 我是不希望打包的要怎么弄？

**Comment by favoyang** [comment]
No support for excluding rules at the moment. But you can try using a regex instead.

For this structure,
```
Assets
Assets/ui
Assets/ui/feat-1
Assets/ui/feat-1/background.png
Assets/ui/feat-2
Assets/ui/feat-2/background.png
Assets/ui/test
Assets/ui/test/background.png
```

Wildcard `Assets/ui/*` will get below (mixed files and directory, not a good practice)
```
Assets/ui/feat-1
Assets/ui/feat-1/background.png
Assets/ui/feat-2
Assets/ui/feat-2/background.png
Assets/ui/test
Assets/ui/test/background.png
``` 

Regex `^Assets/ui/(?!test)(.+)/(.+)` will get below, sounds like what you want?

```
Assets/ui/feat-1/background.png
Assets/ui/feat-2/background.png
```

**Comment by favoyang** [comment]
BTW, http://regexstorm.net/tester is a good tool to test your C# regex rules.

**Comment by favoyang** [comment]
@zuig does it work?

**Comment by zuig** [comment]
yes, it works ,Thanks a lot!!
