### ISSUE TITLE
about ${PATH[-1]} , Is not convenience for long path to get file name.

### ISSUE THREAD

**Issue by zuig** [favoyang/unity-addressable-importer#44]
Assets/Sprites/cat/foo.png

${PATH[-1]} equal "cat", but sometimes i hope to get the name "foo.png",  i have to use ${PATH[3]} .  
and these is no way  to get the file name without suffix.

Assets/floder1/floder2/floder3/floder4/floder5/floder6/floder7/floder8/floder9/floder10/floder11/floder12/floder13/floder14/floder15/foo.png
if my project path is very long , i need to count the number to get the name "foo.png".

Is that any way to get the file name convenience?

**Comment by favoyang** [comment]
The feature is originally designed for "Group Replacement", set filename as a group name is rare, so it's not supported.

I guess you're using the "[Address Replacement](https://github.com/favoyang/unity-addressable-importer/blob/master/Documentation~/AddressableImporter.md#address-replacement)" feature? For now, regex is your friend, you can use a smart regex to capture the filename.

But I agree that adding variables like FILENAME and EXTNAME is convenient.

**Comment by zuig** [comment]
yes, Wildcard is an easy way to use, if provide FILENAME and EXTNAME to use. it will be more powerful. 

For now, a smart regex can solve my problem.
