### ISSUE TITLE
[Feature Request] Support the creating of dynamic labels

### ISSUE THREAD

**Issue by gtoto007** [favoyang/unity-addressable-importer#47]
Hi,

When I defined the rules for creating a group, I would like to specific a dynamic label. The dynamic label would be to follow the same rules to create a dynamic name group. 
Example :
| Asset Path             | Rule Path                                     | Label Replacement               | Result           |
|------------------------|-----------------------------------------------|-----------------------------------|------------------|
| `Assets/cat/cat01.png` | `Assets/(?<category>[^/]+)/(.*)\.png` | `${category}`            | cat        |

I'd like to **add my contribution to the project by developing this feature**. Is it possibile? Do you have advice or contraindications?

**Comment by favoyang** [comment]
I cannot remember why the importer didn't support dynamic labels in the first place. Maybe the label is not a popular way to attribute dynamic assets, so most people use dynamic groups with static labels.

Seems doable if it's possible to create a label programmatically. You take the dynamic groups (group replacement) as a reference for syntax and so on.

https://github.com/favoyang/unity-addressable-importer/blob/master/Documentation~/AddressableImporter.md#group-replacement

Notice that the importer has a `labelMode` to present whether a label is override-able after the first creation. For dynamic labels, it seems should be set to `Replace`.

**Comment by gtoto007** [comment]
Thank you for answer.

I am thinking of adding a "Label Dynamics" field. It will be an array of strings and each string label will support syntax such as group replacement.
For any dynamic label, if it does not exist, the label will be created, otherwise the reference to the existing label will be retrieved and added to the resource.

Even if this new feature will allow you to use existing labels, is it still correct that I leave support for the use of static labels in order not to create backwards compatibility problems?

**Comment by favoyang** [comment]
Adding a new field to keep the backwards compatibility sounds good to me.
