### ISSUE TITLE
Import Settings Inspector should be less clustered, clearer separation between rules

### ISSUE THREAD

**Issue by laicasaane** [favoyang/unity-addressable-importer#59]
#### Bug category

- [x] Importer: issues related to the importer behaviours or UI.
- [ ] ODIN: issues related to the Odin integration.
- [ ] Documentation
- [ ] Others

#### Steps to reproduce

- Add many rules to the `AddressableImportSettings`
- See the input boxes are too close between rules and make the inspector visually too clustered, hard to navigate

#### What is expected?

- Rules should be clearly separated from each other by a larger margin between them

#### What is actually happening?

- Input boxes are too close, rules inspector feels clustered

#### Other relevant information

- Affect me in both Light and Dark mode 

![image](https://user-images.githubusercontent.com/1594982/147406032-b620a7f8-d83a-4270-82f9-2ba3fb33209e.png)

**Comment by laicasaane** [comment]
Some thoughts about a better UI
- Each rule should be expandable
- `Group Name` will the the title of each rule
- Label-related settings should be a sub-expandable too (for I've never work with labels)

**Comment by favoyang** [comment]
@laicasaane thanks for the suggestions for UI. All of them seem reasonable.

My time is a bit tight. This project goes to a lower priority. If you want to work on them, I'll be happy to review and merge a PR.

**Comment by laicasaane** [comment]
I'll work on this since it's been in my head for quite a while already.

**Comment by favoyang** [comment]
Sounds great.
