### ISSUE TITLE
Support multiple AddressableImportSettings instances

### ISSUE THREAD

**Issue by ese9** [favoyang/unity-addressable-importer#66]
Hello.

When I have a lot of rules for my assets I wan't to split them into different AddressableImportSettings for better usability. Also have some cases when I wan't disable some of them without deleting from list (for debug or as temporary decision)

I can contribute this feature to the project, if you find it useful :)

A few screenshots of what it looks like:

![Screenshot_3](https://user-images.githubusercontent.com/38282199/150650017-2b81681d-1e78-4b1a-92dd-d3788a6dac55.png)
![Screenshot_4](https://user-images.githubusercontent.com/38282199/150650019-f8180b32-98a8-4a43-bb7a-a4f4035a83e5.png)

**Comment by favoyang** [comment]
@all-contributors please add @ese9 for code.

**Comment by favoyang** [comment]
Solved by #77, thanks for the contribution by @ese9 and @teck124.
