### ISSUE TITLE
Checking seems not ignoring folder ends with ~

### ISSUE THREAD

**Issue by fantasyz** [favoyang/unity-addressable-importer#72]
#### Bug category

Importer: issues related to the importer behaviours.

Unity ignore certain folder when named in certain ways.
https://docs.unity3d.com/Manual/SpecialFolders.html

#### Steps to reproduce
Create this path:

Assets/FolderTest/Item1/Backup~/abc.png
Assets/FolderTest/Item1/abc.png

Create rule to match path "Assets/FolderTest/*"
Add rule to group "$Path[-1]"

Run re-check on that FolderTest, 

#### What is expected?

group with "Backup~" not created because it is hidden folder to Unity.

#### What is actually happening?

"Backup~" groups created.

#### Other relevant information

- OS (Win/Mac/Linux/Others):
- Unity version: 2021.2
- Addressables version: latest
- Unity Addressable Importer version: latest

P.S
The group is empty inside. The logic does ignored the files under hidden folder but the group itself should also not to be created if possible.

**Comment by favoyang** [comment]
@allcontributors please add @fantasyz for bug.
