### ISSUE TITLE
Package Path Support?

### ISSUE THREAD

**Issue by iDreamsOfGame** [favoyang/unity-addressable-importer#88]
## Feature request

Can this tool support the package path like "Packages/com.unity.images-library/Example/Images/image.png"?
[https://docs.unity3d.com/Manual/upm-assets.html](url)

**Comment by favoyang** [comment]
Yes, it does.

Notice that no matter where your package is hosted (on a registry, a local tarball, or a custom folder), Unity normalized the path to  `Packages/tld.domain.package-name`. The import rule needs to follow that.

e.g. For a local package named `com.example.mycustompackage` located at `Packages/MyCustomPackage`. The rule should be something like `Packages/MyCustomPackage/*.png`.

```
Packages/
  MyCustomPackage
    package.json # com.example.mycustompackage
    myimage.png
```

If it's not working for you, please be more specific about your use case.
